# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '省市联动工具' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'STPopup'
    pod 'Masonry'
    pod 'MJExtension'
  # Pods for 省市联动工具

end
